In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
df = pd.read_csv('archive/quotes.csv')

In [7]:
df.describe()

            Volume
count  1321.000000
mean      6.384557
std       2.234144
min       1.000000
25%       5.000000
50%       7.000000
75%       8.000000
max      10.000000

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1321 entries, 0 to 1320
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Volume    1321 non-null   int64
 1   Topic     1321 non-null   object
 2   SubTopic  1321 non-null   object
 3   URL       1321 non-null   object
 4   Date      6 non-null      object
 5   Text      1321 non-null   object
dtypes: int64(1), object(5)
memory usage: 62.0+ KB

In [10]:
df.sample(20)

,Volume,Topic,SubTopic,URL,Date,Text
508,6,Epistles - Second Series,XLVII Brother disciples,https://en.wikisource.org/wiki/The_Complete_Wo...,NaN,"[""XLVII\n"", ""(Translated from Bengali)\n"", ""NE..."
499,6,Epistles - Second Series,XXXVIII Doctor,https://en.wikisource.org/wiki/The_Complete_Wo...,NaN,"[""\n"", ""XXXVIII\n"", ""\n"", ""KHETRI,\n"", ""27th A..."
735,7,Notes Of Class Talks And Lectures,On Questioning The Competency Of The Guru,https://en.wikisource.org/wiki/The_Complete_Wo...,NaN,"[""\n"", ""\nIn the course of a conversation Swam..."
402,5,Conversations and Dialogues,VI - X Shri Priya Nath Sinha,https://en.wikisource.org/wiki/The_Complete_Wo...,NaN,"[""\n"", ""VI\n"", ""Reminiscences\u2014The Problem..."
722,7,Conversations And Dialogues : Miscellaneous,XXXIV,https://en.wikisource.org/wiki/The_Complete_Wo...,NaN,"[""\n"", ""\""I make the distinction between relig..."
1186,9,Letters - Fifth Series,CXLII Sister Christine,https://en.wikisource.org/wiki/The_Complete_Wo...,NaN,"[""\n"", ""CXLII\n"", ""To Sister Christine\n"", ""TE..."
25,1,Patanjali's Yoga Aphorisms,Concentration: Its Practice,https://en.wikisource.org/wiki/The_Complete_Wo...,NaN,"[""\n"", ""PATANJALI'S YOGA APHORISMSCHAPTER IICO..."
334,5,Epistles - First Series,IC Joe,https://en.wikisource.org/wiki/The_Complete_Wo...,NaN,"[""\n"", ""IC\n"", ""\n"", ""\nMy Dear Joe,(Miss Jose..."
701,7,Conversations And Dialogues : From the Diary o...,XVI,https://en.wikisource.org/wiki/The_Complete_Wo...,NaN,"[""\n"", ""\nThe disciple has come to the Math to..."
418,6,Lectures and Discourses,Concentration and Breathing,https://en.wikisource.org/wiki/The_Complete_Wo...,NaN,"[""\n"", ""CONCENTRATION AND BREATHING\n"", ""\n"", ..."
443,6,Notes Of Class Talks And Lectures,Fragmentary Notes On The Ramayana,https://en.wikisource.org/wiki/The_Complete_Wo...,NaN,"[""Worship Him who alone stands by us, whether ..."
1175,9,Letters - Fifth Series,CXXXI Nivedita,https://en.wikisource.org/wiki/The_Complete_Wo...,NaN,"[""\n"", ""CXXXI\n"", ""To Sister Nivedita\n"", ""[Ea..."
65,2,Jnana Yoga,The Cosmos: The Microcosm,https://en.wikisource.org/wiki/The_Complete_Wo...,NaN,"[""\n"", ""CHAPTER XII\n"", ""THE COSMOS\n"", ""The M..."
28,1,Patanjali's Yoga Aphorisms,Appendix - References To Yoga,https://en.wikisource.org/wiki/The_Complete_Wo...,NaN,"[""\nAPPENDIX\nREFERENCES TO YOGA\n\n"", ""\n"", ""..."
232,4,Translation: Poems,A Hymn to the Divinity of Shri Ramakrishna,https://en.wikisource.org/wiki/The_Complete_Wo...,NaN,"[""\n"", ""A HYMN TO THE DIVINITY OF SHRI RAMAKRI..."
706,7,Conversations And Dialogues : From the Diary o...,XXI,https://en.wikisource.org/wiki/The_Complete_Wo...,NaN,"[""\n"", ""\nSwamiji is staying at the Math nowad..."
1213,9,Letters - Fifth Series,CLXIX Christina,https://en.wikisource.org/wiki/The_Complete_Wo...,NaN,"[""\n"", ""CLXIX\n"", ""To Sister Christine\n"", ""C/..."
686,7,Conversations And Dialogues : From the Diary o...,I,https://en.wikisource.org/wiki/The_Complete_Wo...,NaN,"[""\n"", ""\nSwamiji was staying at the time at t..."
127,3,Lectures from Colombo to Almora,Reply to the Address of Welcome at Pamban,https://en.wikisource.org/wiki/The_Complete_Wo...,NaN,"[""\n"", ""REPLY TO THE ADDRESS OF WELCOME AT PAM..."
990,8,Epistles - Fourth Series,CXLIII Mary,https://en.wikisource.org/wiki/The_Complete_Wo...,NaN,"[""\n"", ""CXLIII\n"", ""To Miss Mary Hale\n"", ""RID..."